language: rust
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx
matrix:
    allow_failures:
        - rust: nightly
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update && sudo apt-get install -y libfuse-dev; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew cask install osxfuse; fi
